FROM node:22.20.0-alpine3.21 AS deps

WORKDIR /app
RUN corepack enable

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .


FROM deps AS development
ENV NODE_ENV=development

COPY --from=deps /app/node_modules ./node_modules
COPY . .

EXPOSE 5173

CMD ["sh", "-c", "pnpm run dev"]