services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: react_app
    ports:
      - "5173:80"
    restart: unless-stopped
    environment:
      - VITE_BASE_URL=${VITE_BASE_URL}