FROM node:22.20.0-alpine3.21 AS deps

WORKDIR /app
RUN corepack enable

COPY package.json pnpm-lock.yaml ./

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install

COPY . .
RUN pnpm run build


FROM nginx:alpine3.22 AS production
COPY --from=deps /app/dist /usr/share/nginx/html
COPY --from=deps /app/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]